'use strict';

export const SET_ALBUM_LIST = 'SET_ALBUM_LIST';
export const SET_ALBUM_DETAIL = 'SET_ALBUM_DETAIL';
export const APPEND_TO_ALBUM_LIST = 'APPEND_TO_ALBUM_LIST';
export const CHANGE_PAGE_TURN_ANIMATE = 'CHANGE_PAGE_TURN_ANIMATE';
export const SET_JUMP_PAGE = 'SET_JUMP_PAGE';